### ISSUE TITLE
Servis za dohvaćanje kategorija

### ISSUE THREAD

**Issue by ispeh** [dpersic/HZZ#1]
Kreirati projekt RESTapi tipa ClassLibrary unutar kojeg je potrebno definirati klasu REST koja ima metodu GetWorkCategories(). Metoda pozivom rest api-ja vraća i parsira JSON u listu objekata klase Category.

**Comment by dpersic** [comment]
Znači unutar projekta(solution-a) kreiram class-u REST koja je slicna classi  Crud u LV5 ? 
I class-u Category koja je slicna classi User (get, set), ako sam ja dobro shvatio zadataka?

**Comment by dpersic** [comment]
![class_library](https://user-images.githubusercontent.com/33121920/33807207-4f875b9c-ddd3-11e7-8f2c-72d6f8a79070.png)
Ovako sam to ja napravio, pa me zanima jel to valja ?

**Comment by ispeh** [comment]
Postavite kod na ovaj repozitorij (nećemo preko slike gledat kod ). Za testiranje servisa najbolje je da napravite testnu konzolnu aplikaciju na kojoj ćete nešto ispisat. Ovako izgleda u redu, ali najbolje je probat na testu.

**Comment by dpersic** [comment]
Kod koji sam napravio postavio sam ga na repozitoriji. Baca mi erorr kod JArray parse, prilikom testiranja u testnoj konzoli.
![error-parse](https://user-images.githubusercontent.com/33121920/33841155-35b795d2-de97-11e7-941a-842cc5094083.png)

**Comment by ispeh** [comment]
7. stranica na predlošku 2. LV, uokvireno i označeno sa uskličnikom

**Comment by dpersic** [comment]
Nikako ne uspijevam napraviti foreach petlju, ako stavim JObject više ne mogu koristiti GetValue, već JToken , a za to ne mogu nikako naći pravi prijemer na Stacku. Jel može pomoć oko te sintakse kako bi trebala ići ?
