### ISSUE TITLE
Klasa Category

### ISSUE THREAD

**Issue by ispeh** [dpersic/HZZ#2]
Kreirati klasu Category  u servisu za dohvaćanje kategorija i poslova.

**Comment by dpersic** [comment]
Unutar klase Category dodao sam slijedece: id, description, created i url. 
Jel je to dovoljno ili da jos nesto ubacim ?

**Comment by ispeh** [comment]
Možete dodati još i position, tako da nam raspored bude isti kao i na HZZ-u
